FROM php:8.4.14-apache

COPY . /var/www/html

RUN apt-get update && apt-get install -y \
        libssl-dev \
        libcurl4-openssl-dev \
    && docker-php-ext-install curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
EXPOSE 80